version: '3.9'
services:
  front:
    build: .
    working_dir: /front
    volumes:
      - ./front:/front
      - node_modules:/front/node_modules
    ports:
      - 3000:3000
      - 5555:5555
    command: npm run dev
    environment:
      -  WATCHPACK_POLLING=true next dev
  db:
    image: mysql:8.3.0
    volumes:
      - db:/ver/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - /front/.env
volumes:
  node_modules:
  db: